### PR TITLE
support building on JDK 11

### PR DESCRIPTION
**Pull request by SethTisue**
this is desirable for the Scala community build, but also
desirable in general

### CODE REVIEW

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by SethTisue** [comment]
gah, there is no Scala.js version available for both 2.12.7 and 2.13.0-M4, hence the CI failure

if Travis likes the followup wip commit, I'll squash

**Comment by SethTisue** [comment]
squashed, but there is still:

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n.expecty#expecty_2.13.0-M5;0.11.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

I've opened https://github.com/eed3si9n/expecty/issues/7 on it

we can leave this PR open for now, it's serving its immediate purpose already in the community build

**Comment by xuwei-k** [comment]
https://github.com/scopt/scopt/pull/205

**Comment by SethTisue** [comment]
rebased, but now it's failing because minitest isn't M5 friendly yet. I'll deal with that next.

**Comment by SethTisue** [comment]
for now let's just wait on https://github.com/monix/minitest/issues/23

**Comment by SethTisue** [comment]
Travis, you are perspicacious indeed in your praise for my brilliant pull request.

I happened to notice that the build logs include Scala Native stuff (`travis_setup.sh`) even though there don't appear to be any Scala Native jobs in the matrix.

@eed3si9n I'm unclear about the "matrix" section, why it is the way it is (why are some combinations missing?) and whether I've updated it exactly right. so you might run a skeptical eye over that before merging.

**Comment by ashawley** [comment]
Sorry, I didn't see this PR, and jumped in line and fixed 2.13.0-M5 in #208.  This will annoyingly cause conflicts you need to resolve, but the good news is that we made a lot of the same changes.

**Comment by SethTisue** [comment]
no worries! rebased, and Travis still likes it.

and the matrix makes sense now, I think. (except that it's a little weird that the Scala Native entry has `TEST_PROJECT` set to `SCALA_JS` but I don't think it actually matters, and in any case it's orthogonal to this PR)

**Comment by eed3si9n** [comment]
I am guessing the matrix situation is mostly due to the availability of the test dependencies?

**Pull request merged**
