### PR TITLE
Add implicit for parsing URL option

### PR DESCRIPTION
**Pull request by aaabramov**

### CODE REVIEW

**Comment by aaabramov** [comment]
@eed3si9n hi, any idea why this is failing?

**Comment by eed3si9n** [comment]
Not sure. Just restarted the job.

**Comment by aaabramov** [comment]
@eed3si9n Added tests for URI and URL readers.

**Comment by aaabramov** [comment]
@eed3si9n sorry for noise, this one is ready to be reviewed

**Review by eed3si9n — APPROVED** [review]
Looks good
Could you squash your commits plz?

**Comment by aaabramov** [comment]
Done. Waiting for travis

**Pull request merged**
