### PR TITLE
Extended `termination()` function to pass through exit code.

### PR DESCRIPTION
**Pull request by metasim**
Strawman implementation for discussion in issue #73. Went for termination code pass through approach rather than anticipating use cases with some other abstraction.

### CODE REVIEW

**Comment by metasim** [comment]
@eed3si9n Any feedback on this PR?

**Comment by eed3si9n** [comment]
Sorry I haven't had time to look into it much, but I feel like `exitCode: Int` is too specific to the `exit`, as opposed to something like `Either[String, Unit]`, which could turn into throwing exception or rage quit (`sys.exit(1)`)

**Comment by metasim** [comment]
@eed3si9n What's the benefit of `Either[String, Unit]` over `Option[String]`?

**Comment by eed3si9n** [comment]
`Some(x)` representing error state is confusing to me.

**Comment by metasim** [comment]
@eed3si9n  Gotcha. 

Still feel like `Either[String, Unit]` doesn't provide enough explicit context on what the receiver should do with the `Left[String]` value, but I can't think of anything better at the moment, short of creating a `TerminationMessage` case class or somesuch with a `isError` flag. 

That said, I'll code up the `Either[String, Unit]` approach when I get a chance.

**Comment by eed3si9n** [comment]
Closing this in favor of #96

**Pull request closed without merging**
