### PR TITLE
Scala 2.13.0

### PR DESCRIPTION
**Pull request by krizalys**
* Added support for stable Scala 2.13.0; updated some dependencies as needed
* Made Scala 2.13.0 the default Scala version
* Kept supporting Scala 2.10.7; had too keep the former minitest version for this Scala version

### CODE REVIEW

**Comment by krizalys** [comment]
@eed3si9n What do you think of this?

**Comment by krizalys** [comment]
@eed3si9n any update on this?

**Review by eed3si9n — APPROVED** [review]
LGTM

**Comment by eed3si9n** [comment]
@krizalys Thanks for the contribution!

**Pull request merged**
