### PR TITLE
drop Scala 2.10 support and simplify build

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @eed3si9n, @ashawley?

**Comment by SethTisue** [comment]
motivation for dropping 2.10:

* the recent addition of Scala 2.13 and JDK 11 to the matrix made for an awfully big matrix, let's economize
* Scala 2.10 is pretty much obsolete at this point, anyone stuck using it should be fine also sticking with whatever scopt version they're already using
* supporting additional Scala versions tends to be a drag on maintenance

the other improvements in the PR are just gravy.

**Comment by ashawley** [comment]
I wonder if while you're at it you can drop the `sonatype-public` resolver in `build.sbt`?  I'm not sure why it's there so it doesn't seem necessary, but I am not an expert.

**Comment by eed3si9n** [comment]
Here's the download report for the month of September 2018:

scopt_usage

- Scala 2.11 JVM: 215167 (63%)
- Scala 2.12 JVM: 96,359 (28%)
- Scala 2.10 JVM: 28,896 (8%)
- Scala 2.8.1 JVM: 334 (0%)
- Scala 2.9.2 JVM: 296 (0%)

So if we are purely talking about simplifying the matrix and reducing the maintenance burden vs impact to the user community, we might consider dropping Scala.JS and Scala Native support instead.

The fact that Scala 2.11 JVM number is 2x the Scala 2.12 is a hint that the major constituency of scopt is Spark and Flink users. Maybe among them Scala 2.10 is still just one version behind?

**Comment by ashawley** [comment]
Given automated builds, I never know what to take from download statistics.  The Scala version percentages seems consistent with the JetBrains user survey:
https://www.jetbrains.com/research/devecosystem-2018/scala/

**Comment by ashawley** [comment]
Since the artifacts for Native and Scala.js have only been available a year, it would seem unfair to compare them to Scala 2.10 which has been out for 5-6 years.

**Comment by SethTisue** [comment]
I agree with Aaron about Scala Native and Scala.js, it doesn't seem relevant to me here, I can see the analogy you are making, but they're really separate issues. Scala Native and Scala.js are hoped to keep growing in the future; Scala 2.10 usage will definitely only keep dropping.

I have no strong opinion about dropping Scala 2.10 support. It's fine to just close the PR if you like, once discussion has wound down.

**Pull request closed without merging**
