### PR TITLE
issue 271 fix

### LINKED ISSUE #271: empty children list causes exception
An empty child list causes an exception:
```sh
[error] Exception in thread "main" scala.MatchError: List() (of class scala.collection.immutable.Nil$)
[error]         at scopt.OParser.children(OParser.scala:131)
[error]         at rparser.es.es-cli$package$.parser(es-cli.scala:63)
[error]         at rparser.Main$.run(Main.scala:91)
```
I think the code here causes the issue as it does not handle the empty list match.

```scala
def children(cs: OParser[_, C]*): OParser[A, C] = {
    cs.toList match {
      case List(c) =>
        val childList = c.toList
        val childListModified = c.toList map { _.parent(head) }
        OParser(head, rest ::: childListModified)
      case x :: xs =>
        children(OParser.sequence(x, xs: _*))
    }
```

### PR DESCRIPTION
**Pull request by aappddeevv**
Fixes #271 

271 fix and test, which failed until the fix occurred

### CODE REVIEW

**Comment by aappddeevv** [comment]
It looks like all the oraclejdk builds failed but the openjdk ones did. I'm not sure how I can resolve this in order to get this merged in.

**Comment by avdv** [comment]
> It looks like all the oraclejdk builds failed but the openjdk ones did. I'm not sure how I can resolve this in order to get this merged in.

there's already PR #268 taking care of that (I guess)

**Comment by eed3si9n** [comment]
#268 failed a while back due to some CI issues I guess, but I was able to restart the job and merge it now.

**Comment by eed3si9n** [comment]
@aappddeevv Looks good. Could you rebase against the latest so Travis CI would run?

**Comment by aappddeevv** [comment]
I'm pretty screwed my PR up trying to rebase it. I can just resubmit if that makes it easier.

**Comment by eed3si9n** [comment]
I can patch it.

**Comment by eed3si9n** [comment]
Closing this in favor of https://github.com/scopt/scopt/pull/274.

**Pull request closed without merging**
