### PR TITLE
add Read[Seq] and Read[Map]

### PR DESCRIPTION
**Pull request by melrief**
Add the possibility to read csv arguments and parse them as Seq or Map

### CODE REVIEW

**Comment by eed3si9n** [comment]
Thanks for the pull request.
I recently had discussion on #53 on this feature, but what are the use cases for `--foo 1,2,3` and `--foo true=true,false=false`?
Do you have example of comma-separated options, or comma-and-equal separated options from some tool or parsing library?

**Comment by melrief** [comment]
For instance, [Hadoop](http://hadoop.apache.org/) can read files, jars and archives from the command line and the arguments are all comma-separated values. For details see [GenericOptionsParser](https://hadoop.apache.org/docs/r1.0.4/api/org/apache/hadoop/util/GenericOptionsParser.html) description.

Similarly also [Spark](https://spark.apache.org/) reads files and jars from the command line. See [SparkSubmitArguments](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/deploy/SparkSubmitArguments.scala#L344) for details.

In my case, I use it at work where I need a map from kafka topics to the number of partitions in input when we use the [Kafka with Spark](https://spark.apache.org/docs/1.0.1/api/java/org/apache/spark/streaming/kafka/KafkaUtils.html#createStream%28org.apache.spark.streaming.StreamingContext,%20java.lang.String,%20java.lang.String,%20scala.collection.immutable.Map,%20org.apache.spark.storage.StorageLevel%29). I was trying to do `--kafka-topics topic1=1,topic2=3...` and so I created this patch.

**Comment by eed3si9n** [comment]
ok. They sound like pretty good use cases. I'll merge this in. /cc @AlessandroEmm

**Comment by eed3si9n** [comment]
Could you send me another pull req documenting this feature in README please?

**Pull request merged**
